# Assignment 4: Bills Actions

**Sally Choi**  

**DATASCI 530**

## Introduction


#### **Key Findings:**

In [9]:
# Import libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [33]:
bills_actions = pd.read_csv("bills_actions.csv")
bills_actions.value_counts
bills_actions.dtypes

Congress        int64
bill_number     int64
bill_type      object
action         object
main_action    object
category       object
member_id       int64
dtype: object

In [34]:
# get distinct bill identifiers
bills_actions[["Congress", "bill_type", "bill_number"]].drop_duplicates().shape[0]
bills_actions[["Congress", "bill_type", "bill_number"]].nunique

<bound method DataFrame.nunique of       Congress bill_type  bill_number
0          116         s         1029
1          116         s         1031
2          116         s         1160
3          116         s         1199
4          116         s         1208
...        ...       ...          ...
3298       116        hr            9
3299       116        hr            9
3300       116        hr            9
3301       116        hr            9
3302       116        hr            9

[3303 rows x 3 columns]>

In [35]:
# combine these columns to identify each bill
bills_actions["bill_identifiers"] = (
    bills_actions["Congress"].astype(str) + "-" +
    bills_actions["bill_type"] + "-" +
    bills_actions["bill_number"].astype(str))

print("Total number of bills:", len(bills_actions))
print("Distinct bills:", len(pd.unique(bills_actions["bill_identifiers"])))

bills_actions.dtypes

Total number of bills: 3303
Distinct bills: 1494

Congress             int64
bill_number          int64
bill_type           object
action              object
main_action         object
category            object
member_id            int64
bill_identifiers    object
dtype: object

In [28]:
# category percentages
category_percent = (bills_actions["category"].value_counts() / len(bills_actions) * 100)

category_percent.round(2).to_frame(name="Percent of rows")

                              Percent of rows
category
amendment                               46.29
house bill                              27.31
senate bill                             15.56
house resolution                         7.08
senate resolution                        1.82
house joint resolution                   0.67
house concurrent resolution              0.61
senate concurrent resolution             0.42
senate joint resolution                  0.24

In [29]:
# main action percentages
bills_actions["main_action"].nunique()
bills_actions["main_action"].unique()

action_percent = (bills_actions["main_action"].value_counts() / len(bills_actions) * 100)

action_percent.round(2).to_frame(name="Percent of rows")

                                               Percent of rows
main_action
house floor actions                                      30.88
house amendment offered                                  25.07
senate committee/subcommittee actions                    13.14
other house amendment actions                            12.02
senate amendment proposed (on the floor)                  8.66
house committee/subcommittee actions                      6.60
reported to senate                                        1.09
senate committee report filed after reporting             1.00
other senate amendment actions                            0.54
resolving differences -- house actions                    0.42
senate floor actions                                      0.39
house discharge petition filed                            0.09
resolving differences -- senate actions                   0.09

### How many House floor actions are associated with bills in the “Senate bills” category?